USE COURSE_MANAGEMENT_TEST;

INSERT INTO GENRE (DESCRIPTION) VALUES ("Male");
INSERT INTO GENRE (DESCRIPTION) VALUES ("Female");
INSERT INTO ADDRESS (ZIP, STREET) VALUES ("08500", "Carrer Nou 1");
INSERT INTO ADDRESS (ZIP, STREET) VALUES ("08500", "Carrer Nou 2");
INSERT INTO STUDENT (FIRST_NAME, LAST_NAME, GENRE, ADDRESS) VALUES ("Nick", "Drake", 1, 1);
INSERT INTO STUDENT (FIRST_NAME, LAST_NAME, GENRE, ADDRESS) VALUES ("Laura", "Pausini", 1, 2);
INSERT INTO COURSE (NAME, YEAR) VALUES ("Singing I", 2024);
INSERT INTO COURSE (NAME, YEAR) VALUES ("Singing II", 2025);
INSERT INTO STUDENT_COURSE (STUDENT, COURSE) VALUES (1, 1);
INSERT INTO STUDENT_COURSE (STUDENT, COURSE) VALUES (2, 2);