/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("buildlogic.java-application-conventions")
}

dependencies {
    implementation(project(":domain"))
    implementation(project(":domain-implementations:jpa"))
    implementation(project(":domain-implementations:jdbc"))

    implementation("com.github.freva:ascii-table:1.8.0")
    implementation("org.apache.logging.log4j:log4j-core:2.23.1")
}

application {
    // Define the main class for the application.
    mainClass = "cat.uvic.teknos.coursemanagement.backoffice.App"
}
